"""Custom exception hierarchy for pipeline errors."""

from .pipeline_exceptions import (
    ChunkingError,
    ChunkTokenLimitExceededError,
    DocumentAlreadyIngestedException,
    DocumentIngestionError,
    EmbeddingBatchFailureError,
    EmbeddingError,
    EmbeddingModelUnavailableError,
    EmbeddingTokenOverflowError,
    EmptyChunkError,
    FigureDescriptionError,
    PDFCorruptedError,
    PDFNoTextLayerError,
    PDFParseError,
    PDFPasswordProtectedError,
    PipelineBaseException,
    RegistryConnectionError,
    RegistryError,
    RegistryJobNotFoundError,
    VectorStoreDiskFullError,
    VectorStoreError,
    VectorStoreWriteError,
    VisionLLMQuotaExceededError,
    VisionLLMTimeoutError,
)

__all__ = [
    "PipelineBaseException",
    "DocumentIngestionError",
    "PDFParseError",
    "PDFCorruptedError",
    "PDFPasswordProtectedError",
    "PDFNoTextLayerError",
    "FigureDescriptionError",
    "VisionLLMTimeoutError",
    "VisionLLMQuotaExceededError",
    "DocumentAlreadyIngestedException",
    "ChunkingError",
    "ChunkTokenLimitExceededError",
    "EmptyChunkError",
    "EmbeddingError",
    "EmbeddingModelUnavailableError",
    "EmbeddingBatchFailureError",
    "EmbeddingTokenOverflowError",
    "VectorStoreError",
    "VectorStoreWriteError",
    "VectorStoreDiskFullError",
    "RegistryError",
    "RegistryConnectionError",
    "RegistryJobNotFoundError",
]
